### ISSUE TITLE
gee -distribute doesnt evenly distribute 

### ISSUE THREAD

**Issue by 0xtavian** [hahwul/gee#29]
@hahwul 
I love gee. Im trying to work it more and more into axiom https://github.com/pry0cc/axiom. 

take a file with x number of lines and distribute for example
```
seq 1 6 > file | gee -distribute 1 2 3

cat 1 | wc -l
3
cat 2 | wc -l
2
cat 3 | wc -l
1
```

Gee should instead distribute evenly, expected result:

```
cat 1 | wc -l
2
cat 2 | wc -l
2
cat 3 | wc -l
2
```

**Comment by hahwul** [comment]
I'm on it 😎

**Comment by hahwul** [comment]
## Test
```
$ seq 1 6 > file | gee -distribute 1 2 3
```

```
☁  ~  cat 1
1
4
5
☁  ~  cat 2
2
6
☁  ~  cat 3
3
```

https://github.com/hahwul/gee/blob/eb4d930ece9e72b9d1ba46eeecfd3e11998f2dba/pkg/gee/gee.go#L68

## Fixed?
```
$ seq 1 6 > file | ./gee -distribute 1 2 3
1
2
3
4
5
6
☁  gee [main] ⚡  cat 1
1
4
☁  gee [main] ⚡  cat 2
2
5
☁  gee [main] ⚡  cat 3
3
6
```

**Comment by hahwul** [comment]
Hi @0xtavian 
I've just fixed this issue and it's being released. 
I'll close the issue! If you have any problems after using it, please re-open :D

## Update
from source
```
▶ GO111MODULE=on go get -v github.com/hahwul/gee
```

with homebrew
```
▶ brew update gee
```

**Comment by 0xtavian** [comment]
Before updating, you can see one has 2X more vs the rest
<img width="367" alt="Screen Shot 2021-07-23 at 1 36 31 PM" src="https://user-images.githubusercontent.com/21030907/126827296-9b52f547-6a7e-43a6-be4a-bcf56c8eb8dd.png">


After updating - WOOT! thank you <3
<img width="385" alt="Screen Shot 2021-07-23 at 1 38 33 PM" src="https://user-images.githubusercontent.com/21030907/126827327-f0cc5917-f3d2-4f4d-8335-74a0ef9b2ef7.png">
